name: Blender Addon Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., v1.2.1)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install zipfile36

    - name: Build addon
      run: |
        mkdir build
        cp -r * build/ || true
        cd build
        zip -r ../Optimized-Tris-to-Quads-Converter.zip *
      
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${{ github.ref_name }}
        if [ "$VERSION" == "" ]; then
          VERSION=${{ github.event.inputs.version }}
        fi
        gh release create $VERSION \
          --title "Release $VERSION" \
          --notes "Release $VERSION" \
          Optimized-Tris-to-Quads-Converter.zip
