name: Build Blender Addon

on:
  workflow_dispatch: # Allows manual trigger of the action

jobs:
  build-addon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create addon folder structure
        run: |
          ADDON_NAME="Optimized-Tris-to-Quads-Converter"
          mkdir -p $ADDON_NAME
          
          # Copy all add-on files from the root directory to the folder
          cp -r * $ADDON_NAME/
          
      - name: Archive the addon for release
        run: |
          ADDON_NAME="Optimized-Tris-to-Quads-Converter"
          zip -r $ADDON_NAME.zip $ADDON_NAME

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: blender-addon
          path: Optimized-Tris-to-Quads-Converter.zip
