runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install zipfile36

    - name: Build addon
      run: |
      mkdir -p build/OptimizedTrisToQuadsConverter
      cp -r * build/OptimizedTrisToQuadsConverter/ || true
      cd build
      zip -r ../Optimized-Tris-to-Quads-Converter.zip OptimizedTrisToQuadsConverter
      
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${{ github.ref_name }}
        if [ "$VERSION" == "" ]; then
          VERSION=${{ github.event.inputs.version }}
        fi
        gh release create $VERSION \
          --title "Release $VERSION" \
          --notes "Release $VERSION" \
          Optimized-Tris-to-Quads-Converter.zip
