name: Blender Addon Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install zipfile36

    - name: Build addon
      run: |
        mkdir build
        cp -r * build/ || true
        cd build
        zip -r ../Optimized-Tris-to-Quads-Converter.zip *
      
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --notes "Release ${{ github.ref_name }}" \
          Optimized-Tris-to-Quads-Converter.zip