name: Build Blender Addon

on:
  workflow_dispatch: # Allows manual trigger of the action

jobs:
  build-addon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List directory contents for debugging
        run: |
          echo "Listing root directory contents..."
          ls -la

      - name: Create addon folder structure
        run: |
          ADDON_NAME="Optimized-Tris-to-Quads-Converter"
          mkdir -p $ADDON_NAME
          
          echo "Copying files into $ADDON_NAME"
          # Copy all add-on files from the root directory to the folder, excluding the .git and workflow directories
          rsync -av --exclude=".git" --exclude=".github" --exclude="$ADDON_NAME" . $ADDON_NAME/
          
          echo "Listing $ADDON_NAME contents..."
          ls -la $ADDON_NAME
          
      - name: Archive the addon for release
        run: |
          ADDON_NAME="Optimized-Tris-to-Quads-Converter"
          zip -r $ADDON_NAME.zip $ADDON_NAME
          echo "Add-on zipped: $ADDON_NAME.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: blender-addon
          path: Optimized-Tris-to-Quads-Converter.zip
