name: Build and Release Blender Addon

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for release'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4 # Updated to use Node.js 20 compatible version
    
    - name: Set up Python
      uses: actions/setup-python@v5 # Updated to use Node.js 20 compatible version
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install zipfile36

    - name: Build addon
      run: |
        mkdir -p build/OptimizedTrisToQuadsConverter
        cp -r * build/OptimizedTrisToQuadsConverter/ || true
        cd build
        zip -r ../Optimized-Tris-to-Quads-Converter.zip OptimizedTrisToQuadsConverter

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${{ github.ref_name }}
        if [ "$VERSION" == "" ]; then
          VERSION=${{ github.event.inputs.version }}
        fi
        gh release create $VERSION \
          --title "Release $VERSION" \
          --notes "Release $VERSION" \
          Optimized-Tris-to-Quads-Converter.zip
